/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.php",
    "./**/*.php",
    "./js/**/*.js",
    "./includes/**/*.php",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        }
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      }
    },
  },
  plugins: [],
  safelist: [
    'bg-blue-500',
    'bg-blue-600',
    'bg-blue-700',
    'bg-green-500',
    'bg-green-600',
    'bg-green-700',
    'bg-red-500',
    'bg-red-600',
    'bg-red-700',
    'bg-yellow-500',
    'bg-yellow-600',
    'bg-yellow-700',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-50',
    'text-white',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-blue-500',
    'text-blue-600',
    'text-green-500',
    'text-red-500',
    'hover:bg-blue-700',
    'hover:bg-green-700',
    'hover:bg-red-700',
    'hover:bg-gray-200',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:shadow-outline',
    'border-gray-300',
    'border-gray-200',
    'rounded-lg',
    'rounded-md',
    'shadow-md',
    'shadow-lg',
    'p-2',
    'p-3',
    'p-4',
    'p-6',
    'p-8',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'py-1',
    'py-2',
    'py-3',
    'm-2',
    'm-4',
    'mt-2',
    'mt-4',
    'mt-6',
    'mt-8',
    'mb-2',
    'mb-4',
    'mb-6',
    'ml-2',
    'mr-2',
    'w-full',
    'w-auto',
    'h-screen',
    'min-h-screen',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'flex',
    'inline-flex',
    'justify-center',
    'items-center',
    'space-x-2',
    'space-x-4',
    'space-y-2',
    'space-y-4',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-center',
    'text-left',
    'text-right'
  ]
}
